from tootanky.champion import BaseChampion

from .aatrox import Aatrox
from .ahri import Ahri
from .akali import Akali
from .akshan import Akshan
from .alistar import Alistar
from .amumu import Amumu
from .anivia import Anivia
from .annie import Annie
from .aphelios import Aphelios
from .ashe import Ashe
from .aurelionsol import AurelionSol
from .azir import Azir
from .bard import Bard
from .belveth import BelVeth
from .blitzcrank import Blitzcrank
from .brand import Brand
from .braum import Braum
from .caitlyn import Caitlyn
from .darius import Darius
from .ezreal import Ezreal
from .irelia import Irelia
from .jarvan import JarvanIV
from .jax import Jax
from .malphite import Malphite
from .missfortune import MissFortune
from .xerath import Xerath
from .zed import Zed
